export interface SeriesInterface {
    characters: Object,
    comics: Object,
    creators: Object,
    description: string,
    endYear: number,
    events: Object,
    id: number,
    modified: string,
    next: any,
    previous: any,
    rating: string,
    resourceURI: string,
    startYear: number,
    stories: Object,
    thumbnail: Object,
    title: string,
    type: string,
    urls: any[]
}